baseURL = "http://example.org/"
languageCode = "es-co"
title = "Magic Dose"
Paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2020"
canonifyurls = true

[author]
  name = "JPC"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "We reinvents hydration"
  cover = "images/user.jpg"
  author = "JPC"
  authorlocation = ""
  authorwebsite = ""
  bio= "my bio"
  logo = "" # images/user.png
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "JPC"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  mainSections = ["post"]
